export const REQUEST_LOADING_RESPOSTAS = 'REQUEST_LOADING_RESPOSTAS';
export const REQUEST_REJECTED_RESPOSTAS = 'REQUEST_REJECTED_RESPOSTAS';
export const REQUEST_FULFILLED_RESPOSTAS = 'REQUEST_FULFILLED_RESPOSTAS';
