export const REQUEST_LOADING_CADASTRO = 'REQUEST_LOADING_CADASTRO';
export const REQUEST_REJECTED_CADASTRO = 'REQUEST_REJECTED_CADASTRO';
export const REQUEST_FULFILLED_CADASTRO = 'REQUEST_FULFILLED_CADASTRO';
